version: '3.9'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "npm ci && npm run dev -- --host"
    volumes:
      - .:/app
    ports:
      - "5173:5173"
